### ISSUE TITLE
dataset.csv

### ISSUE THREAD

**Issue by anilpanicker** [DhruvKumar/spark-twitter-sentiment#2]
Hi DhruvKumar,
I was trying to set up the ML job that you described here. I couldn't get the dataset.csv file can you please let me know where can I find the data.
Thanks in advance.
Anil

**Comment by phumlani-mbabela** [comment]
Hi team, what's the format of the training data?

**Comment by anilpanicker** [comment]
It is in csv format

**Comment by phumlani-mbabela** [comment]
How are the fields formated? Don't worry too much, Im going to check the
source code.

**Comment by jaheem** [comment]
any one help with dataset file Thank you

**Comment by caiomsouza** [comment]
Where is the dataset?

**Comment by anilpanicker** [comment]
​
 Sentiment-Analysis-Dataset.zip
https://drive.google.com/file/d/0Bx09lT_03GXnOWQtNjZzU2NiT0E/view?usp=drive_web
​

**Comment by anilpanicker** [comment]
closed
